version: '3-7'

services:
  dim:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.dim.loadbalancer.server.port=8000
      - traefik.http.routers.dim.entrypoints=web
      - traefik.http.routers.dim.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.dim-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.dim.middlewares=dim-https-redirect
      - traefik.http.routers.dim-secure.entrypoints=websecure
      - traefik.http.routers.dim-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.dim-secure.tls=true
      - traefik.http.routers.dim-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
