services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    init: true
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - internal

  db:
    image: postgres:14-alpine
    container_name: postgresql
    init: true
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - internal
    volumes:
      - ./schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data

volumes:
  umami-db-data: {}

networks:
  internal: {}
